### ISSUE TITLE
Build from source results in permission error

### ISSUE THREAD

**Issue by ThatOneCalculator** [kra-mo/hyperplane#16] opened 2024-01-03 21:39 UTC
```sh
git clone https://github.com/kra-mo/hyperplane.git
cd hyperplane
meson setup build
ninja -C build install
```

results in a successful install, but then

`hyperplane` gives `zsh: permission denied: /usr/local/bin/hyperplane`

And the .desktop file gives

![image](https://github.com/kra-mo/hyperplane/assets/44733677/009f8ad1-3516-4892-9396-db5734efe721)

**Comment by kra-mo** [comment] 2024-01-03 21:47
Just `sudo chmod+x /usr/local/bin/hyperplane` for now. Not sure why this happens though as the executable bit is set for the .in file.

**Comment by ThatOneCalculator** [comment] 2024-01-03 21:49
That now results in

```
$ hyperplane --new-window
Traceback (most recent call last):
  File "/usr/local/bin/hyperplane", line 44, in <module>
    from hyperplane import main
ModuleNotFoundError: No module named 'hyperplane'
```

**Comment by ThatOneCalculator** [comment] 2024-01-03 21:50
Also, is there any reason you're going into `/usr/local/*` instead of `/usr/*`?

**Comment by kra-mo** [comment] 2024-01-03 21:59
Yes. `/usr/` is for software installed by your package manager, you don’t want to mess with that. As for the import error, that is probably because `/usr/local/lib/python3.whatever` is not in your `PYTHONPATH`. But may I ask why you’re trying to build the app manually instead of using the Flatpak?

**Comment by ThatOneCalculator** [comment] 2024-01-03 22:02
Mostly for Tinkering and potentially making a PKGBUILD :)

**Comment by kra-mo** [comment] 2024-01-03 22:08
Does [this branch](https://github.com/kra-mo/hyperplane/tree/r-xr-xr-x) fix it for you?

**Comment by kra-mo** [comment] 2024-01-03 22:08
The executable part anyway, the import error is a distro/environment thing

**Comment by ThatOneCalculator** [comment] 2024-01-03 22:16
That fixes the executable part.

**Comment by kra-mo** [comment] 2024-01-03 22:18
Thanks. The other part should be resolved by running it with `PYTHONPATH=/usr/local/lib/python3.12/ hyperplane` (or whichever python version you have, but probably 3.12 because of Arch). It also shouldn't be an issue if the app is installed via a package manager since it would install to `/usr/` instead, which is presumably a Python search path on Arch

**Comment by kra-mo** [comment] 2024-01-03 22:19
Please tell me if the issue is resolved

**Comment by ThatOneCalculator** [comment] 2024-01-03 22:21
Give me a few mins and I can test it.

**Comment by ThatOneCalculator** [comment] 2024-01-03 22:51
Sadly still doesn't work. Tried with `python3.11` since `/usr/local/lib/python3.11/site-packages/hyperplane/ ` does actually exist

**Comment by kra-mo** [comment] 2024-01-03 22:55
It might be `PYTHONPATH=/usr/local/lib/python3.11/site-packages hyperplane` instead. Does that work?

**Comment by ThatOneCalculator** [comment] 2024-01-03 23:04
That works!

**Closed** 2024-01-03 23:04 UTC
Labels: bug
